### ISSUE TITLE
Sender Address

### ISSUE THREAD

**Issue by markusmo** [awesto/djangoshop-sendcloud#7]
Hi
I added a sender address at Sendcloud, but still I get a 500 error, when creating a parcel. I also contacted their support because as far as I could see, everything is correctly implemented here. They told me, that I would have to set my sender address in my REST-call, as it is missing, and they would need that. 

Looking at the api  and your implementation I am quite confused on what I did wrong, as the api states that `sender_address` is an optional field.
Do you have any suggestions?

**Comment by jrief** [comment]
Just tested myself and I can confirm that something doesn't work anymore:
I get a 500 response from Sendcloud.

This used to work. It seems that the REST endpoint at Sendcloud requires additional data in their JSON payload.

**Comment by markusmo** [comment]
https://github.com/awesto/djangoshop-sendcloud/pull/8
Created a pull request

**Comment by markusmo** [comment]
fixed
